name: PHPCS Check and Fix

on:
  push:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install PHP CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHPCS and Auto-fix
        run: |
          ~/.composer/vendor/bin/phpcs --standard=phpcs.xml --colors .
          ~/.composer/vendor/bin/phpcbf --standard=phpcs.xml .

      - name: Clean up
        run: composer global remove squizlabs/php_codesniffer
